ALTER TABLE sites ADD COLUMN prefix TEXT NOT NULL DEFAULT '';
ALTER TABLE sites ADD COLUMN verify_date TIMESTAMPTZ NOT NULL DEFAULT now();
ALTER TABLE sites ADD COLUMN status TEXT NOT NULL DEFAULT 'NOT_VERIFIED'
